Algoritmo "Divisão"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita dois números e realiza a divisão
// Autor(a)   : Gabriel Henrique Alves Rocha
// Data atual : 04/04/2026
Var
// Seção de Declarações das variáveis
num1, num2: inteiro
divisao: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número:")
Leia(num1)
Escreva("Digite um número:")
Leia(num2)
divisao<- num1 / num2
Escreva("A divisão dos números digitados é:",divisao)
Fimalgoritmo