Algoritmo "Multiplicação"
// Disciplina : Lógica de Programação
// Professor  : Jailson Costa dos Santos
// Descrição  : Solicita dois números e realiza a multiplicação
// Autor  : Gabriel Henrique Alves Rocha
// Data atual : 05/04/2026
Var
// Seção de Declarações das variáveis
num1, num2, multiplicacao: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreva("Digite um número:")
Leia(num1)
Escreva("Digite um número:")
Leia(num2)
multiplicacao<- num1 * num2
Escreva("A multiplicação dos números digitados é:",multiplicacao)
Fimalgoritmo